import { useEffect, useState } from "react";
import { useChatbot } from "../../hooks/useChatbot";
import { ChatComposer } from "./ChatComposer";
import { ChatMessageList } from "./ChatMessageList";

export function ChatWidget({ userId }: { userId: string }) {
  const [open, setOpen] = useState(false);
  const { messages, isLoading, error, failedMessage, sendMessage, retryLastMessage, clearMessages } = useChatbot(userId);
  useEffect(() => { if (open) document.getElementById("chatbot-message")?.focus(); }, [open]);
  if (!open) return <button type="button" onClick={() => setOpen(true)} aria-label="Öppna chatbot" aria-expanded={false} className="fixed bottom-5 right-5 z-30 flex h-14 w-14 items-center justify-center rounded-full bg-indigo-600 text-white shadow-lg transition hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-gray-950"><svg aria-hidden="true" width="25" height="25" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M20 11.5a7.5 7.5 0 0 1-7.5 7.5H7l-4 3 1.3-4.2A7.5 7.5 0 1 1 20 11.5Z" /><path d="M8 11.5h.01M12 11.5h.01M16 11.5h.01" /></svg></button>;
  function clearHistory() { if (messages.length > 0 && !window.confirm("Vill du rensa hela chatthistoriken?")) return; clearMessages(); }
  return <section aria-label="Innovia Hub chatbot" className="fixed bottom-4 right-4 z-30 flex h-[min(680px,calc(100vh-2rem))] w-[min(400px,calc(100vw-2rem))] flex-col overflow-hidden rounded-xl border border-gray-200 bg-white shadow-2xl dark:border-gray-700 dark:bg-gray-900"><header className="flex items-center justify-between border-b border-gray-200 px-4 py-3 dark:border-gray-800"><div><h2 className="font-semibold text-gray-900 dark:text-gray-100">Innovia Hub chatbot</h2><p className="text-xs text-gray-500 dark:text-gray-400">Fråga om hur hubben fungerar</p></div><div className="flex items-center gap-1"><button type="button" onClick={clearHistory} className="rounded px-2 py-1 text-xs font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:hover:bg-gray-800 dark:hover:text-gray-100">Rensa</button><button type="button" onClick={() => setOpen(false)} aria-label="Stäng chatbot" className="rounded p-1.5 text-gray-500 hover:bg-gray-100 hover:text-gray-900 dark:hover:bg-gray-800 dark:hover:text-gray-100"><svg aria-hidden="true" width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M6 6l12 12M18 6L6 18" /></svg></button></div></header><ChatMessageList messages={messages} isLoading={isLoading} /><ChatComposer isLoading={isLoading} error={error} failedMessage={failedMessage} onSend={sendMessage} onRetry={retryLastMessage} /></section>;
}
